### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by namnhatpham1995**

### CODE REVIEW

**Comment by lars-sh** [comment]
@namnhatpham1995, please describe, what this Pull Request is about.

Is it about not using curly braces to access characters of a string? As of https://php.net/string#language.types.string.substr that's just the same as using non-curly braces.

Though strangely as of https://php.net/migration74.deprecated#migration74.deprecated.core.array-string-access-curly-brace accessing characters of a string using curly braces seems to be deprecated in PHP 7.4.

Therefore I'd be fine with your Pull Request. Please confirm.

**Comment by lars-sh** [comment]
Btw: If this leads to problems, other pieced of oneye code should be/needs to be fixd, too.

**Comment by namnhatpham1995** [comment]
Sorry for my mistake. I am a student trying to make oneye working  on PHP 8 as a part of my project given by my professor. 
I am working with it and somehow I send pull request by mistake to the master branch of your.

**Comment by lars-sh** [comment]
That sounds great. Just create a Pull Request once you reached some point of compatibility. Feel free to keep those steps small.

So for now I just close this Pull Request. In case that's not intended, simply reopen it again.

**Pull request closed without merging**
